Repository Harsya1/b_camp, pull requests merged in 2025-05, with the labels that each got.

#18 feat: integrate shared preferences for token storage and retrieval in…
  lib/service/database/controller/UserAplikasiController.dart
  lib/service/database/controller/itemCampController.dart
  macos/Flutter/GeneratedPluginRegistrant.swift
  pubspec.lock
  pubspec.yaml
Labels: documentation, duplicate, enhancement, help wanted, wontfix

#21 Revert "feat: add event display section and implement event fetching …
  .vscode/launch.json
  lib/screen/home_dashboard.dart
  lib/service/database/controller/itemCampController.dart
  lib/service/database/controller/itemEventController.dart
Labels: bug, documentation, enhancement

#24 feat: update booking section background color and text content; add c…
  lib/screen/booking_section/booking.dart
  lib/screen/camp_section/camp_detail.dart
  lib/screen/home_dashboard.dart
  lib/screen/search_section.dart
  lib/service/database/controller/itemEventController.dart
Labels: bug, documentation, duplicate, enhancement, wontfix

#25 feat: refactor main app structure; remove dashboard and booking secti…
  lib/main.dart
  lib/screen/dashboard_calender.dart
  lib/screen/dashboard_camp.dart
  lib/screen/home_dashboard.dart
  lib/screen/routes/routes.dart
  lib/screen/test.txt
  lib/service/database/controller/itemCampController.dart
  pubspec.lock
  pubspec.yaml
Labels: documentation, duplicate, help wanted, good first issue, wontfix

#29 feat: enhance camp detail and dashboard screens; implement calendar f…
  lib/screen/camp_section/camp_detail.dart
  lib/screen/dashboard_calender.dart
  lib/screen/dashboard_camp.dart
  pubspec.lock
  pubspec.yaml
Labels: documentation, duplicate, enhancement, good first issue

#30 feat: update dashboard layout; integrate room list and calendar view
  lib/screen/dashboard_calender.dart
  lib/screen/dashboard_camp.dart
  lib/screen/routes/routes.dart
Labels: bug, documentation, duplicate, enhancement

#34 feat: enhance dashboard calendar; update room selection and calendar …
  lib/screen/dashboard_calender.dart
Labels: bug, documentation, good first issue

#35 feat: update navigation and login flow; set initial route to login an…
  lib/main.dart
  lib/screen/dashboard_calender.dart
  lib/screen/dashboard_camp.dart
  lib/screen/login_register_section/login_action.dart
  lib/screen/login_register_section/register_action.dart
  lib/screen/routes/routes.dart
  pubspec.lock
  pubspec.yaml
Labels: documentation, duplicate, enhancement, good first issue, wontfix

#36 feat: update initial route to dashboard calendar and modify drawer la…
  lib/main.dart
  lib/screen/dashboard_calender.dart
  lib/screen/dashboard_camp.dart
Labels: bug, documentation, duplicate, enhancement, good first issue, invalid, wontfix

#40 Dika lego
  lib/main.dart
  lib/screen/booking_section/input_data.dart
  lib/screen/dashboard_calender.dart
  lib/screen/dashboard_camp.dart
  lib/screen/routes/routes.dart
Labels: bug, documentation, duplicate, wontfix

#45 Dika lego
  lib/screen/booking_section/input_data.dart
  lib/screen/camp_section/create_camp.dart
  lib/screen/routes/routes.dart
Labels: bug, documentation, duplicate, enhancement, wontfix

#53 Refactor dashboard camp screen(unused screen); remove register action…
  lib/screen/camp_section/camp_detail.dart
  lib/screen/camp_section/create_camp.dart
  lib/screen/camp_section/create_kamar.dart
  lib/screen/camp_section/crud_camp.dart
  lib/screen/camp_section/detail_kamar.dart
  lib/screen/camp_section/edit_camp.dart
  lib/screen/camp_section/edit_kamar.dart
  lib/screen/camp_section/list_kamar.dart
  lib/screen/camp_section/placeholder_camp.dart
  lib/screen/dashboard_camp.dart
  lib/screen/login_register_section/register_action.dart
  lib/screen/routes/routes.dart
  lib/service/database/controller/UserAplikasiController.dart
  lib/service/database/controller/itemCampController.dart
  lib/service/database/controller/itemEventController.dart
  lib/service/database/controller/itemKamarController.dart
Labels: bug, enhancement, help wanted

#54 Dika lego
  lib/screen/camp_section/crud_camp.dart
  lib/screen/camp_section/detail_kamar.dart
  lib/screen/camp_section/placeholder_camp.dart
  lib/screen/crud_booking.dart
  lib/screen/dashboard_calender.dart
  lib/screen/login_register_section/login_action.dart
  lib/screen/routes/app_drawer.dart
  lib/screen/routes/routes.dart
  pubspec.lock
  pubspec.yaml
Labels: bug, documentation, duplicate, wontfix
